version: '3.8'

services:
  # PostgreSQL 데이터베이스 (공유)
  postgres:
    image: postgres:15-alpine
    container_name: chat-server-rdbms
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: baekgwa
      POSTGRES_PASSWORD: baekgwa1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatuser -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - baekgwa-chat-network

# 볼륨 정의
volumes:
  postgres_data:
    driver: local

# 네트워크 정의
networks:
  baekgwa-chat-network:
    driver: bridge